spack:
  packages:
    castep:
      permissions:
        read: group
        #group: lgcastep
        group: ag-archpc-castep
    orca:
      permissions:
        read: group
        #group: legorca
        group: ag-archpc-orca
    vasp@6:
      permissions:
        read: group
        #group: legvasp6
        group: ag-archpc-vasp6

    # must build with make -j1
    quantum-espresso:
      package_attributes:
        parallel: false

    # make sure everything uses zlib-ng with +new_strategies so we don't end up with multiple binutils
    zlib-api:
      require: 'zlib-ng'

    zlib-ng:
      require:
      - spec: +new_strategies

    # if anything demands a different openmpi, make sure it has the right options
    openmpi:
      require:
      - spec: 'fabrics=ofi schedulers=slurm +legacylaunchers'
      prefer:
      - '@4.1.6'

  specs:
  - matrix:
    - - apr
      - apr-util
      - bcftools@1.16
      - beast2@2.7.4
      - bedtools2@2.31.0
      - bwa@0.7.17
      - cmake
      - curl +libidn2
      - fftw@3.3.10 -mpi -openmp
      - gatk@4.4.0.0
      - git@2.46.2
      - gsl@2.8
      - gzip@1.13
      - hdf5 +cxx +fortran -mpi +hl
      - hdf5 +fortran +mpi +hl
      - htslib@1.17
      - openmpi@4.1.6 fabrics=ofi schedulers=slurm +legacylaunchers
      - python@3.11.6
      - netcdf-c@4.9.2 -mpi
      - netcdf-fortran@4.6.1
      - picard@2.26.2
      - samtools@1.17
      - subversion
      # stop it picking an openblas with threads=openmp purely for package reuse
      - castep@24.1 +libxc ^openblas threads=none
      - castep@23.1 +libxc ^openblas threads=none
      - cp2k@2024.3 
      - gromacs@2024.3 -double
      #- gromacs@2024.3 +double
      - gromacs@2023.5 -double +plumed
      #- gromacs@2023.5 +double +plumed
      - lammps@20240829.1 +mpi +python +amoeba +asphere +bocs +body +bpm +brownian +cg-dna +cg-spica +class2 +colloid +colvars +compress +coreshell +dielectric +diffraction +dipole +dpd-basic +dpd-meso +dpd-react +dpd-smooth +drude +eff +electrode +extra-compute +extra-dump +extra-fix +extra-molecule +extra-pair +fep +granular +interlayer +kspace +lepton +machdyn +manybody +mc +meam +mesont +misc +ml-iap +ml-pod +ml-snap +ml-uf3 +mofff +molecule +openmp +opt +orient +peri +phonon +plugin +poems +qeq +reaction +reaxff +replica +rigid +rheo +shock +sph +spin +srd +tally +uef +voronoi +yaff
      - libxc@6.2.2
      #- namd@2.14 ^charmpp backend=ucx pmi=pmix ^fftw -mpi
      #- namd@3.0.1 ^charmpp backend=ofi pmi=pmix ^fftw -mpi # should be doing this, can't yet
      - namd@3.0.1 ^charmpp backend=ucx pmi=pmix ^fftw -mpi
      #- namd@3.0.1 ^charmpp backend=verbs ^fftw -mpi # not working outside dev
      - netlib-scalapack@2.2.0
      - numactl@2.0.18
      - openblas@0.3.28 threads=none
      - openblas@0.3.28 threads=openmp
      - plumed@2.9.2
      - quantum-espresso@7.4 cflags='-O2' fflags='-O2' # ICE in gcc 12 and 13 vectorisation: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112404
    - - '%gcc@12.3.0'
  - gcc@12.3.0 +binutils

  # Intel compilers built with gcc
  - matrix:
    - - intel-oneapi-compilers@2024.2.1 # there is 2025.1.0
  #   - intel-oneapi-compilers@2023.2.4 # last icc/icpc version
    - - '%gcc@12.3.0'

  concretizer:
    unify: when_possible
  view: false
  include_concrete:
  - /lustre/apps/spack/0.23/deploy/2025-09/spack/var/spack/environments/second_compiler
