[general]
# this setting must be set before use, or the sites will appear as a sibling to this repo
# this is where each periodic site will be created (by default?)
# sites_root = {hpc_spack_root}/../test-spack-sites
sites_root = /apps/spack/0.23/deploy

# No setting for modules root, or build stage, because those are set in a module's spack.yaml

# TODO ? change this to default_spack_version and allow version for new site to be specified in create
spack_version = v0.23.0

[process_env_scripts]
# scripts to be sourced before running spack etc
# note that argument $1 of spdsper receives an absolute path of spack's setup-env.sh for the site in question, 
# which it sources, so that environment can be used to run spack commands
# spack-deps sets up a process environment with software that spack needs, e.g. a system compiler
spd_default = {hpc_spack_root}/spacksites/process-env-scripts/spack-deps.sh
spdr = {hpc_spack_root}/spacksites/process-env-scripts/spack-deps-run.sh
spdsper = {hpc_spack_root}/spacksites/process-env-scripts/spack-deps-spack-env-run.sh
# 9.x uses default (nothing required)

[initial_site_configs]
config_default = {hpc_spack_root}/spacksites/settings/2026-07_myriad/deploy_site_config.yaml
modules_default = {hpc_spack_root}/spacksites/settings/2026-07_myriad/initial_site_modules_rhel-9.6.yaml
packages_default = {hpc_spack_root}/spacksites/settings/2026-07_myriad/initial_site_packages_rhel-9.6.yaml
repos_default = {hpc_spack_root}/spacksites/settings/2026-07_myriad/initial_site_repos.yaml
mirrors_default = {hpc_spack_root}/spacksites/settings/2026-07_myriad/deploy_site_mirrors.yaml

[spack_env_templates]
active_set = {hpc_spack_root}/spacksites/spack-env-templates/slurm/2026-07_myriad
#TODO use this in the code
archive_root = {hpc_spack_root}/spacksites/spack-env-archive
